services:
  - type: web
    name: lifeshift
    runtime: docker
    region: oregon
    plan: free
    dockerfile: ./Dockerfile
    dockerContext: ./
    envVars:
      - key: SPRING_DATASOURCE_URL
        scope: run
      - key: SPRING_DATASOURCE_USERNAME
        scope: run
      - key: SPRING_DATASOURCE_PASSWORD
        scope: run
      - key: GOOGLE_CLIENT_ID
        scope: run
      - key: GOOGLE_CLIENT_SECRET
        scope: run
      - key: GROQ_API_KEY
        scope: run
      - key: GROQ_API_URL
        scope: run
      - key: GROQ_MODEL
        scope: run
      - key: RABBITMQ_HOST
        scope: run
      - key: RABBITMQ_PORT
        scope: run
      - key: RABBITMQ_USERNAME
        scope: run
      - key: RABBITMQ_PASSWORD
        scope: run
      - key: PORT
        value: "8080"
